language: go

install:
 - mkdir -p $GOPATH/src/github.com/ethereum/
 - cd $GOPATH/src/github.com/ethereum/; git clone https://github.com/ethereum/go-ethereum
 - cd $GOPATH/src/github.com/ethereum/go-ethereum/; git remote add fork https://github.com/tbocek/go-ethereum.git
 - git pull --rebase fork master
 - go get ./...
