language: go

go:
- 1.6
- tip

dist: trusty
sudo: required

before_install:
- cd $GOPATH/src/github.com
- mkdir ethereum
- cd ethereum
- git clone https://github.com/ethereum/go-ethereum
- cd go-ethereum
- git checkout develop
- go get github.com/tools/godep
- godep go install ./cmd/abigen
- sudo add-apt-repository -y ppa:ethereum/ethereum-qt
- sudo add-apt-repository -y ppa:ethereum/ethereum
- sudo apt-get -y update
- sudo apt-get -y install cpp-ethereum
- cd

install:
- pwd
- ls -la
- go get -t -v ./smartcontract/...
- go get -t -v
- go generate ./smartcontract/...
- go generate

script:
- pwd
- ls -la
- go get -t -v ./smartcontract/...
- go get -t -v
- go generate ./smartcontract/...
- go generate
- go test -v ./smartcontract/...
- go test -v
