language: go
before_install:
- cd $GOPATH/src/github.com
- mkdir ethereum
- cd ethereum
- git clone https://github.com/ethereum/go-ethereum
- cd go-ethereum
- git checkout develop
- go get github.com/tools/godep
- godep go install ./cmd/abigen
- cd $GOPATH/src/github.com/modum-io/smartcontract
notifications:
  slack:
    secure: PnISdLh3rACbC2fojyZ2HVJXYQfuT6R4FqgygQrKXEuIeTeB02tF05N/FQm4oVMc7tJJNspbmcDleOz8W9p9ViwkTOwMvmp9/zkOWGFU2Kp2NSpfnPQAV7/XV8FY1yoLA8/VFZVdgfNMU2PU8rcbzXGALDXzgEG574DCkxomnAdNhAiQDOBhJvgyrkkcBhQ/y8Y3cYJHOakz7grnZuU5xDigaq1i6pQ0V8LYWcyb5LORuyeNO3Pm7V2BvURcDUhZ2Zfb0QKIia4oyGQihaVUOuOp9SjdYaLLm+RAWdskiQUoziULY68oTtxS1vT4eZTIh3BZhEHHnYkMwJKfDhOF9uFNHlxs7IUIHRV4sSWs/GpU+Ri3sqMUJ2Z6wN0JMxZymqO7zVlu+kIbJiqLct4MfhwwaLe26HzSZo0GdTqdK5QicMMA09BVZj/pPsS6Us4gsIOUphmOVZr1yD4Ahfz825XbBWeq31kve0MVgcGXvX+9oXHH5QpXPk/78A8AhU7caPs793H3DPVQcpSJVX/wucgxKHpfs+I8qmu0vGXeXBiBIkl4YUFVqk2MdWq30Nqdq+lG9sufqDFzrJ0uLakTFF7ll2QLifxrO/8/q+77uO6ec/WzXnolHzcbS/HhyQZOWjQTkZtZvtJ5CpO0AdcwoBWLWRptXk8glCr2FkmyuLM=
