language: go
before_install:
- cd $GOPATH/src/github.com
- mkdir ethereum
- cd ethereum
- git clone https://github.com/ethereum/go-ethereum
- cd go-ethereum
- git checkout develop
- go get github.com/tools/godep
- godep go install ./cmd/abigen

script:
- go get
- go generate
- go test -v ./...
